<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="28785" started-at="2019-03-02T10:59:08Z" finished-at="2019-03-02T10:59:37Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="28785" started-at="2019-03-02T10:59:08Z" finished-at="2019-03-02T10:59:37Z">
      <class name="OrgTest.SelTestClass">
        <test-method status="PASS" signature="setUp()[pri:0, instance:OrgTest.SelTestClass@6ba0ac]" name="setUp" is-config="true" duration-ms="4851" started-at="2019-03-02T16:29:08Z" finished-at="2019-03-02T16:29:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testA()[pri:0, instance:OrgTest.SelTestClass@6ba0ac]" name="testA" duration-ms="3545" started-at="2019-03-02T16:29:13Z" finished-at="2019-03-02T16:29:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method status="PASS" signature="getTestResult(org.testng.ITestResult)[pri:0, instance:OrgTest.SelTestClass@6ba0ac]" name="getTestResult" is-config="true" duration-ms="2" started-at="2019-03-02T16:29:17Z" finished-at="2019-03-02T16:29:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testA status=SUCCESS method=SelTestClass.testA()[pri:0, instance:OrgTest.SelTestClass@6ba0ac] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestResult -->
        <test-method status="FAIL" signature="testB()[pri:0, instance:OrgTest.SelTestClass@6ba0ac]" name="testB" duration-ms="16599" started-at="2019-03-02T16:29:17Z" finished-at="2019-03-02T16:29:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at OrgTest.SelTestClass.testB(SelTestClass.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB -->
        <test-method status="PASS" signature="getTestResult(org.testng.ITestResult)[pri:0, instance:OrgTest.SelTestClass@6ba0ac]" name="getTestResult" is-config="true" duration-ms="1476" started-at="2019-03-02T16:29:33Z" finished-at="2019-03-02T16:29:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testB status=FAILURE method=SelTestClass.testB()[pri:0, instance:OrgTest.SelTestClass@6ba0ac] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestResult -->
        <test-method status="PASS" signature="testDown()[pri:0, instance:OrgTest.SelTestClass@6ba0ac]" name="testDown" is-config="true" duration-ms="1616" started-at="2019-03-02T16:29:35Z" finished-at="2019-03-02T16:29:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDown -->
        <test-method status="PASS" signature="closeExtentReport()[pri:0, instance:OrgTest.SelTestClass@6ba0ac]" name="closeExtentReport" is-config="true" duration-ms="658" started-at="2019-03-02T16:29:36Z" finished-at="2019-03-02T16:29:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeExtentReport -->
      </class> <!-- OrgTest.SelTestClass -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
