<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="64417" started-at="2019-03-02T10:49:15Z" finished-at="2019-03-02T10:50:20Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="64417" started-at="2019-03-02T10:49:15Z" finished-at="2019-03-02T10:50:20Z">
      <class name="OrgTest.SelTestClass">
        <test-method status="PASS" signature="setUp()[pri:0, instance:OrgTest.SelTestClass@ec5a4a]" name="setUp" is-config="true" duration-ms="5352" started-at="2019-03-02T16:19:15Z" finished-at="2019-03-02T16:19:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testA()[pri:0, instance:OrgTest.SelTestClass@ec5a4a]" name="testA" duration-ms="4494" started-at="2019-03-02T16:19:21Z" finished-at="2019-03-02T16:19:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method status="PASS" signature="getTestResult(org.testng.ITestResult)[pri:0, instance:OrgTest.SelTestClass@ec5a4a]" name="getTestResult" is-config="true" duration-ms="10" started-at="2019-03-02T16:19:25Z" finished-at="2019-03-02T16:19:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testA status=SUCCESS method=SelTestClass.testA()[pri:0, instance:OrgTest.SelTestClass@ec5a4a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestResult -->
        <test-method status="FAIL" signature="testB()[pri:0, instance:OrgTest.SelTestClass@ec5a4a]" name="testB" duration-ms="50983" started-at="2019-03-02T16:19:25Z" finished-at="2019-03-02T16:20:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at OrgTest.SelTestClass.testB(SelTestClass.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB -->
        <test-method status="PASS" signature="getTestResult(org.testng.ITestResult)[pri:0, instance:OrgTest.SelTestClass@ec5a4a]" name="getTestResult" is-config="true" duration-ms="1790" started-at="2019-03-02T16:20:16Z" finished-at="2019-03-02T16:20:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testB status=FAILURE method=SelTestClass.testB()[pri:0, instance:OrgTest.SelTestClass@ec5a4a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestResult -->
        <test-method status="PASS" signature="testDown()[pri:0, instance:OrgTest.SelTestClass@ec5a4a]" name="testDown" is-config="true" duration-ms="1715" started-at="2019-03-02T16:20:18Z" finished-at="2019-03-02T16:20:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDown -->
      </class> <!-- OrgTest.SelTestClass -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
